In [1]:
import os
from tensorflow.keras.models import load_model

2024-03-16 22:46:27.477120: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-03-16 22:46:27.477150: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
v = 2
N = 6

project_dir_path = os.environ["NIR_1_sem_magistracy"]
# код с моделями layer взят из NeuralNetwork_11_first_layer_tests
dir_model = 'saved_models'
layer = 'first'
path_dir_model = os.path.join(project_dir_path, dir_model, layer, f'_{v}')
print(path_dir_model)
saved_models = list(os.walk(path_dir_model))[0]
save_name = f'model_{layer}_{N}_{v}'
path = os.path.join(path_dir_model, save_name)
path

/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_2

'/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_2/model_first_6_2'

In [3]:
model = load_model(path)
model

2024-03-16 22:46:33.206913: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-03-16 22:46:33.206968: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-03-16 22:46:33.207014: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Ivan-PC): /proc/driver/nvidia/version does not exist
2024-03-16 22:46:33.207992: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [4]:
#Test on Aleksashina 1 - Bad result in '00:00:35.000', '00:00:37.000'

In [5]:
data_dir = 'Data'
data_dir = os.path.join(project_dir_path, data_dir)
csv_file = "Participant 1_Aleksashina_Analysis 1_video_20190607_114857_detailed.csv"
csv_path = os.path.join(data_dir, csv_file)
csv_path

'/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/Data/Participant 1_Aleksashina_Analysis 1_video_20190607_114857_detailed.csv'

In [6]:
import pandas as pd

In [7]:
df_test = pd.read_csv(csv_path, sep='\t', skiprows = lambda i: i in range(8))

In [8]:
df_first = df_test.columns[0]
df_test.columns = df_test.columns[1:].insert(-2, 'UNKNOWN')
df_test.insert(0, df_first, df_test.index)
df_test

,Video Time,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted,Valence,Arousal,...,Action Unit 12 - Right - Lip Corner Puller,Action Unit 14 - Right - Dimpler,Action Unit 15 - Right - Lip Corner Depressor,Action Unit 20 - Right - Lip Stretcher,Action Unit 43 - Right - Eyes Closed,Stimulus,Event Marker,UNKNOWN,Participant Name,Analysis Index
00:00:00.000,00:00:00.000,0.973121,0.019527,0.000404,0.043879,0.004099,0.000322,0.001946,-0.024352,0.255187,...,0.0,0.017570,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:00:00.100,00:00:00.100,0.974289,0.020129,0.000382,0.042413,0.004014,0.000298,0.001820,-0.022284,0.260074,...,0.0,0.032680,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:00:00.200,00:00:00.200,0.975457,0.020731,0.000361,0.040947,0.003930,0.000273,0.001693,-0.020216,0.264960,...,0.0,0.047791,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:00:00.300,00:00:00.300,0.975028,0.020480,0.000345,0.042622,0.003916,0.000256,0.001549,-0.022143,0.269347,...,0.0,0.060645,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:00:00.400,00:00:00.400,0.974542,0.020394,0.000326,0.044417,0.003831,0.000235,0.001438,-0.024022,0.273202,...,0.0,0.068510,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
00:01:50.900,00:01:50.900,0.969587,0.016939,0.000846,0.051552,0.004851,0.000162,0.000609,-0.034614,0.317045,...,0.0,0.199020,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:01:51.000,00:01:51.000,0.969071,0.017130,0.000856,0.052158,0.004848,0.000168,0.000615,-0.035027,0.316651,...,0.0,0.202110,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:01:51.100,00:01:51.100,0.968842,0.017460,0.000885,0.052096,0.004807,0.000172,0.000620,-0.034636,0.316144,...,0.0,0.196561,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:01:51.200,00:01:51.200,0.968608,0.018322,0.000899,0.052130,0.004756,0.000176,0.000617,-0.033808,0.315641,...,0.0,0.196161,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:01:51.300,00:01:51.300,0.968453,0.019037,0.000889,0.052191,0.004726,0.000178,0.000603,-0.033154,0.315094,...,0.0,0.193525,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1

In [9]:
seven_fields = [
    'Neutral', 
    'Happy', 
    'Sad', 
    'Angry', 
    'Surprised', 
    'Scared', 
    'Disgusted'
]

In [10]:
seven_vector_test = df_test[seven_fields]
seven_vector_test

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:00.000,0.973121,0.019527,0.000404,0.043879,0.004099,0.000322,0.001946
00:00:00.100,0.974289,0.020129,0.000382,0.042413,0.004014,0.000298,0.001820
00:00:00.200,0.975457,0.020731,0.000361,0.040947,0.003930,0.000273,0.001693
00:00:00.300,0.975028,0.020480,0.000345,0.042622,0.003916,0.000256,0.001549
00:00:00.400,0.974542,0.020394,0.000326,0.044417,0.003831,0.000235,0.001438
...,...,...,...,...,...,...,...
00:01:50.900,0.969587,0.016939,0.000846,0.051552,0.004851,0.000162,0.000609
00:01:51.000,0.969071,0.017130,0.000856,0.052158,0.004848,0.000168,0.000615
00:01:51.100,0.968842,0.017460,0.000885,0.052096,0.004807,0.000172,0.000620
00:01:51.200,0.968608,0.018322,0.000899,0.052130,0.004756,0.000176,0.000617
00:01:51.300,0.968453,0.019037,0.000889,0.052191,0.004726,0.000178,0.000603

In [11]:
pa_fields =     [
    'Valence',
    'Arousal'
]

In [12]:
pa_vector_test = df_test[pa_fields]
pa_vector_test

               Valence   Arousal
00:00:00.000 -0.024352  0.255187
00:00:00.100 -0.022284  0.260074
00:00:00.200 -0.020216  0.264960
00:00:00.300 -0.022143  0.269347
00:00:00.400 -0.024022  0.273202
...                ...       ...
00:01:50.900 -0.034614  0.317045
00:01:51.000 -0.035027  0.316651
00:01:51.100 -0.034636  0.316144
00:01:51.200 -0.033808  0.315641
00:01:51.300 -0.033154  0.315094

[1114 rows x 2 columns]

In [13]:
import sys

lib_dir = 'lib'
lib_dir_path = os.path.join(project_dir_path, lib_dir)
sys.path.append(lib_dir_path)
from nn_train.neural_network import NeuralNetwork

In [14]:
nn_test = NeuralNetwork(pa_vector_test, seven_vector_test, model)

/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/lib/nn_train/neural_network.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df_x[field] = self.df_x[field].apply(lambda entry: float(entry))
/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/lib/nn_train/neural_network.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df_y[field] = self.df_y[field].apply(lambda entry: float(entry))

In [15]:
#Будем дообучаться с '00:00:30.000' до '00:00:38.000'

In [16]:
df_x = nn_test.get_df_xy('00:00:30.000', '00:00:38.000')
df_x

               Valence   Arousal
00:00:30.000  0.725731  0.339765
00:00:30.100  0.737862  0.339765
00:00:30.200  0.726528  0.339271
00:00:30.300  0.712153  0.338363
00:00:30.400  0.709858  0.337356
...                ...       ...
00:00:37.600  0.002470  0.274409
00:00:37.700 -0.014269  0.274178
00:00:37.800 -0.012094  0.273958
00:00:37.900  0.001319  0.273736
00:00:38.000  0.015823  0.273556

[81 rows x 2 columns]

In [17]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 19-23%, Happy - 44-56%, Angry - 66-55%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:30.000,0.132133,0.756668,0.001669,0.030937,0.000408,0.000671,0.001260
00:00:30.100,0.130447,0.768046,0.001361,0.030184,0.000499,0.000711,0.001268
00:00:30.200,0.147706,0.755921,0.001117,0.029393,0.000589,0.000680,0.001202
00:00:30.300,0.164955,0.739512,0.001299,0.027358,0.000643,0.000609,0.001229
00:00:30.400,0.171592,0.735537,0.001367,0.025679,0.000635,0.000525,0.001322
...,...,...,...,...,...,...,...
00:00:37.600,0.227043,0.561071,0.000104,0.558601,0.000207,0.000137,0.000757
00:00:37.700,0.225937,0.553081,0.000104,0.567351,0.000206,0.000137,0.000822
00:00:37.800,0.227376,0.557128,0.000104,0.569222,0.000204,0.000138,0.000881
00:00:37.900,0.228799,0.561518,0.000105,0.560199,0.000205,0.000137,0.000959
00:00:38.000,0.229891,0.565980,0.000106,0.550158,0.000208,0.000136,0.000998

In [18]:
nn_test.predict()

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:30.000,0.186736,0.789888,0.000001,0.000003,0.030717,0.002372,6.497028e-07
00:00:30.100,0.178198,0.799650,0.000001,0.000002,0.030563,0.002329,5.656410e-07
00:00:30.200,0.186426,0.790351,0.000001,0.000003,0.030659,0.002369,6.467268e-07
00:00:30.300,0.197434,0.777997,0.000001,0.000003,0.030754,0.002420,7.684621e-07
00:00:30.400,0.199714,0.775633,0.000001,0.000003,0.030685,0.002427,7.961509e-07
...,...,...,...,...,...,...,...
00:00:37.600,0.877208,0.048463,0.013941,0.027846,0.033302,0.007159,4.947692e-03
00:00:37.700,0.875660,0.034524,0.017285,0.035327,0.033320,0.007479,6.238282e-03
00:00:37.800,0.876027,0.036134,0.016840,0.034304,0.033293,0.007435,6.065398e-03
00:00:37.900,0.877529,0.047505,0.014217,0.028415,0.033237,0.007176,5.053610e-03
00:00:38.000,0.879098,0.063573,0.011828,0.023143,0.033184,0.006906,4.145861e-03

In [19]:
len(df_x)

81

In [20]:
import numpy as np

In [21]:
x = []
for i in range(len(df_x)):
    x.append((df_x['Valence'][i], df_x['Arousal'][i])) 
    
x = np.array(x)

In [22]:
x.shape

(81, 2)

In [23]:
y = []
for i in range(len(df_y)):
    y.append(tuple(df_y[col][i] for col in df_y.columns)) 
y = np.array(y)

In [24]:
y.shape

(81, 7)

In [25]:
model.fit(x=x, y=y, epochs=10, batch_size=30)

Epoch 1/10
3/3 [==============================] - 0s 3ms/step - loss: 0.0710
Epoch 2/10
3/3 [==============================] - 0s 3ms/step - loss: 0.0701
Epoch 3/10
3/3 [==============================] - 0s 4ms/step - loss: 0.0691
Epoch 4/10
3/3 [==============================] - 0s 3ms/step - loss: 0.0682
Epoch 5/10
3/3 [==============================] - 0s 4ms/step - loss: 0.0673
Epoch 6/10
3/3 [==============================] - 0s 2ms/step - loss: 0.0663
Epoch 7/10
3/3 [==============================] - 0s 4ms/step - loss: 0.0654
Epoch 8/10
3/3 [==============================] - 0s 3ms/step - loss: 0.0645
Epoch 9/10
3/3 [==============================] - 0s 3ms/step - loss: 0.0636
Epoch 10/10
3/3 [==============================] - 0s 3ms/step - loss: 0.0627

In [26]:
# Пройдём тест заново

In [27]:
df_x = nn_test.get_df_xy('00:00:00.000', '00:00:00.100')
df_x

               Valence   Arousal
00:00:00.000 -0.024352  0.255187
00:00:00.100 -0.022284  0.260074

In [28]:
df_y = nn_test.get_df_xy(xy = 'y') #Neutral - 97%, Happy - 1-2%, Angry - 4%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:00.000,0.973121,0.019527,0.000404,0.043879,0.004099,0.000322,0.001946
00:00:00.100,0.974289,0.020129,0.000382,0.042413,0.004014,0.000298,0.001820

In [29]:
nn_test.predict() #Neutral - 76% - err - 6%, Happy - 2-3% - err - 1-2%, Angry - 7-8% - err - 3-4% - ХОРОШО.

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:00.000,0.837358,0.032381,0.017426,0.048093,0.031912,0.007891,0.006528
00:00:00.100,0.833358,0.033000,0.016353,0.045437,0.032370,0.007882,0.006095

In [30]:
df_x = nn_test.get_df_xy('00:00:16.000', '00:00:17.000')
df_x

               Valence   Arousal
00:00:16.000  0.982274  0.763761
00:00:16.100  0.982497  0.761543
00:00:16.200  0.982457  0.759395
00:00:16.300  0.982780  0.757186
00:00:16.400  0.983181  0.754926
00:00:16.500  0.983513  0.752694
00:00:16.600  0.983897  0.750396
00:00:16.700  0.983741  0.748033
00:00:16.800  0.982967  0.745634
00:00:16.900  0.982504  0.743361
00:00:17.000  0.982369  0.741136

In [31]:
df_y = nn_test.get_df_xy(xy = 'y') # Happy - 98%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:16.000,0.007980,0.984054,0.000013,0.001780,0.002200,0.001339,0.000060
00:00:16.100,0.007884,0.984246,0.000013,0.001749,0.002323,0.001302,0.000059
00:00:16.200,0.007840,0.984331,0.000013,0.001875,0.002367,0.001226,0.000057
00:00:16.300,0.007679,0.984653,0.000014,0.001873,0.002433,0.001246,0.000056
00:00:16.400,0.007520,0.984970,0.000014,0.001789,0.002598,0.001347,0.000054
00:00:16.500,0.007385,0.985240,0.000014,0.001727,0.002701,0.001379,0.000054
00:00:16.600,0.007240,0.985530,0.000014,0.001633,0.002647,0.001379,0.000053
00:00:16.700,0.007345,0.985320,0.000014,0.001580,0.002596,0.001452,0.000057
00:00:16.800,0.007730,0.984552,0.000013,0.001585,0.002543,0.001457,0.000060
00:00:16.900,0.007821,0.984368,0.000013,0.001865,0.002409,0.001359,0.000064
00:00:17.000,0.007792,0.984427,0.000013,0.002058,0.002319,0.001242,0.000064

In [32]:
nn_test.predict() #Happy - 94% - err - 4% - ХОРОШО.

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:16.000,0.009376,0.982864,9.619174e-10,5.012802e-09,0.084593,0.001554,4.161118e-10
00:00:16.100,0.009442,0.982788,9.762718e-10,5.078599e-09,0.084013,0.001552,4.236905e-10
00:00:16.200,0.009519,0.982692,9.935789e-10,5.159324e-09,0.083468,0.001550,4.324477e-10
00:00:16.300,0.009581,0.982625,1.007055e-09,5.220239e-09,0.082892,0.001548,4.397717e-10
00:00:16.400,0.009643,0.982561,1.020154e-09,5.278883e-09,0.082303,0.001545,4.470389e-10
00:00:16.500,0.009707,0.982492,1.034073e-09,5.341557e-09,0.081728,0.001542,4.546645e-10
00:00:16.600,0.009771,0.982425,1.048048e-09,5.404068e-09,0.081138,0.001540,4.624256e-10
00:00:16.700,0.009863,0.982309,1.069998e-09,5.506157e-09,0.080563,0.001538,4.735615e-10
00:00:16.800,0.009987,0.982136,1.101229e-09,5.654198e-09,0.080014,0.001539,4.886163e-10
00:00:16.900,0.010093,0.981994,1.127845e-09,5.779072e-09,0.079484,0.001539,5.017534e-10
00:00:17.000,0.010182,0.981882,1.149899e-09,5.880927e-09,0.078952,0.001537,5.130519e-10

In [33]:
df_x = nn_test.get_df_xy('00:00:21.000', '00:00:23.000')
df_x

               Valence   Arousal
00:00:21.000  0.964579  0.663201
00:00:21.100  0.943782  0.659207
00:00:21.200  0.871111  0.652940
00:00:21.300  0.762326  0.644623
00:00:21.400  0.640243  0.633058
00:00:21.500  0.520727  0.618742
00:00:21.600  0.413288  0.603645
00:00:21.700  0.323662  0.588063
00:00:21.800  0.251679  0.572172
00:00:21.900  0.194049  0.555099
00:00:22.000  0.148148  0.536985
00:00:22.100  0.111093  0.518199
00:00:22.200  0.080803  0.499630
00:00:22.300  0.054733  0.481918
00:00:22.400  0.034692  0.465653
00:00:22.500  0.019820  0.451096
00:00:22.600  0.007910  0.438177
00:00:22.700 -0.006161  0.426671
00:00:22.800 -0.020030  0.416402
00:00:22.900 -0.035617  0.407217
00:00:23.000 -0.047857  0.399033

In [34]:
df_y = nn_test.get_df_xy(xy = 'y') #Neutral - 1-95%, Happy - 96-1%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:21.000,0.019636,0.966993,0.000121,0.002414,0.002644,0.002096,0.000165
00:00:21.100,0.051523,0.946047,0.000221,0.002265,0.002547,0.002061,0.000355
00:00:21.200,0.135548,0.875374,0.000303,0.004263,0.002576,0.001903,0.000715
00:00:21.300,0.247636,0.770754,0.000351,0.008427,0.002592,0.001688,0.000968
00:00:21.400,0.365667,0.655739,0.000364,0.015496,0.002655,0.001459,0.001092
00:00:21.500,0.477339,0.544180,0.000356,0.023453,0.002761,0.001233,0.001120
00:00:21.600,0.576351,0.443905,0.000341,0.030617,0.002846,0.001026,0.001090
00:00:21.700,0.660592,0.357482,0.000767,0.033820,0.002812,0.000842,0.001407
00:00:21.800,0.730230,0.284993,0.004092,0.033314,0.002743,0.000681,0.002124
00:00:21.900,0.786891,0.225365,0.007646,0.031317,0.002668,0.000547,0.002939
00:00:22.000,0.831870,0.176788,0.012967,0.028640,0.002633,0.000438,0.003709
00:00:22.100,0.867497,0.137732,0.016150,0.026639,0.002577,0.000354,0.004042
00:00:22.200,0.894690,0.106713,0.017925,0.025911,0.002472,0.000289,0.004167
00:00:22.300,0.913525,0.082282,0.019553,0.027548,0.002337,0.000237,0.004469
00:00:22.400,0.927302,0.063380,0.020318,0.028688,0.002183,0.000197,0.004664
00:00:22.500,0.937785,0.048936,0.019899,0.029117,0.002059,0.000164,0.004699
00:00:22.600,0.946148,0.037900,0.018283,0.029990,0.002009,0.000141,0.004482
00:00:22.700,0.950496,0.029679,0.015991,0.035840,0.002078,0.000128,0.004055
00:00:22.800,0.952492,0.023617,0.013573,0.043648,0.002294,0.000120,0.003566
00:00:22.900,0.951661,0.018998,0.011318,0.054615,0.002543,0.000117,0.003085
00:00:23.000,0.950978,0.015523,0.009315,0.063379,0.002740,0.000121,0.002662

In [35]:
nn_test.predict() #Neutral - 7-84% - err - 6-11%, Happy - 93-3% - err - 3% - Допустимо!

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:21.000,0.014729,0.976043,2.670166e-09,1.272728e-08,0.062783,0.001531,1.302303e-09
00:00:21.100,0.016486,0.973240,3.579257e-09,1.689227e-08,0.062838,0.001585,1.720379e-09
00:00:21.200,0.023727,0.961453,9.374064e-09,4.300931e-08,0.064557,0.001798,4.236842e-09
00:00:21.300,0.040506,0.934298,3.928094e-08,1.729217e-07,0.067432,0.002173,1.616869e-08
00:00:21.400,0.073303,0.882720,1.996183e-07,8.373315e-07,0.070315,0.002684,7.420380e-08
00:00:21.500,0.128844,0.800279,1.003919e-06,4.006688e-06,0.072575,0.003296,3.391243e-07
00:00:21.600,0.207446,0.693323,4.365126e-06,1.662850e-05,0.074155,0.003959,1.357092e-06
00:00:21.700,0.298773,0.581933,1.523243e-05,5.567632e-05,0.074807,0.004606,4.436908e-06
00:00:21.800,0.389524,0.483171,4.269190e-05,1.505017e-04,0.074558,0.005194,1.185561e-05
00:00:21.900,0.472554,0.402029,1.008524e-04,3.441274e-04,0.073371,0.005706,2.711691e-05
00:00:22.000,0.503830,0.244318,2.108812e-04,7.375777e-04,0.070655,0.006325,5.838084e-05
00:00:22.100,0.524435,0.138601,3.968477e-04,1.426935e-03,0.067498,0.006903,1.142754e-04
00:00:22.200,0.546301,0.084620,6.819069e-04,2.492964e-03,0.064407,0.007391,2.031326e-04
00:00:22.300,0.567692,0.054711,1.100659e-03,4.068375e-03,0.061540,0.007826,3.380179e-04
00:00:22.400,0.588070,0.039316,1.622856e-03,6.017476e-03,0.058957,0.008157,5.109608e-04
00:00:22.500,0.606792,0.031047,2.206057e-03,8.159608e-03,0.056689,0.008391,7.086098e-04
00:00:22.600,0.623457,0.025825,2.847612e-03,1.048455e-02,0.054728,0.008574,9.303391e-04
00:00:22.700,0.637252,0.020368,3.740489e-03,1.378116e-02,0.053081,0.008826,1.244128e-03
00:00:22.800,0.649076,0.016016,4.852980e-03,1.791269e-02,0.051667,0.009090,1.642197e-03
00:00:22.900,0.658779,0.012068,6.384462e-03,2.368981e-02,0.050472,0.009419,2.200067e-03
00:00:23.000,0.667685,0.009703,7.975042e-03,2.963200e-02,0.049409,0.009675,2.789944e-03

In [36]:
df_x = nn_test.get_df_xy('00:00:36.000', '00:00:37.000')
df_x

               Valence   Arousal
00:00:36.000 -0.214707  0.260461
00:00:36.100 -0.215263  0.259816
00:00:36.200 -0.183632  0.259228
00:00:36.300 -0.147168  0.258936
00:00:36.400 -0.117836  0.258876
00:00:36.500 -0.091053  0.258876
00:00:36.600 -0.067193  0.262077
00:00:36.700 -0.040169  0.265263
00:00:36.800 -0.026193  0.267305
00:00:36.900 -0.011659  0.269329
00:00:37.000  0.001245  0.270993

In [37]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 19-23%, Happy - 44-56%, Angry - 66-55%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:36.000,0.189787,0.446914,0.000195,0.661620,0.000168,0.000154,0.000912
00:00:36.100,0.184945,0.455178,0.000176,0.670441,0.000158,0.000153,0.000907
00:00:36.200,0.189195,0.478034,0.000159,0.661666,0.000151,0.000145,0.000883
00:00:36.300,0.196710,0.498410,0.000149,0.645577,0.000148,0.000137,0.000835
00:00:36.400,0.201433,0.516213,0.000143,0.634049,0.000147,0.000128,0.000784
00:00:36.500,0.206537,0.530494,0.000139,0.621547,0.000150,0.000119,0.000746
00:00:36.600,0.213259,0.539001,0.000133,0.606194,0.000154,0.000111,0.000718
00:00:36.700,0.216637,0.549414,0.000127,0.589583,0.000160,0.000107,0.000705
00:00:36.800,0.218805,0.557725,0.000121,0.583918,0.000159,0.000102,0.000706
00:00:36.900,0.219156,0.565864,0.000115,0.577523,0.000164,0.000101,0.000695
00:00:37.000,0.220346,0.569772,0.000110,0.568527,0.000171,0.000101,0.000689

In [38]:
nn_test.predict() # Лучше, но плохо пока что. Neutral - err - 33-49%, Happy - err - 34-40%, 
# Angry - err - 18-52%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:36.000,0.736836,0.000789,0.067086,0.215069,0.030977,0.011222,0.039015
00:00:36.100,0.736709,0.000785,0.067120,0.215069,0.030889,0.011210,0.039179
00:00:36.200,0.768728,0.001366,0.065154,0.202848,0.031624,0.010970,0.033758
00:00:36.300,0.801910,0.002578,0.062955,0.189528,0.032539,0.010709,0.028378
00:00:36.400,0.820695,0.004428,0.055841,0.165010,0.033032,0.010324,0.022967
00:00:36.500,0.824629,0.007825,0.039890,0.117281,0.032812,0.009570,0.015917
00:00:36.600,0.825150,0.012763,0.028747,0.083855,0.032934,0.008971,0.011165
00:00:36.700,0.826141,0.022174,0.019825,0.056757,0.033029,0.008334,0.007487
00:00:36.800,0.826291,0.029376,0.016292,0.046097,0.033117,0.008025,0.006066
00:00:36.900,0.826539,0.039275,0.013284,0.037067,0.033200,0.007715,0.004876
00:00:37.000,0.826879,0.050714,0.011088,0.030520,0.033260,0.007449,0.004021

In [39]:
df_x = nn_test.get_df_xy('00:00:42.000', '00:00:42.500')
df_x

               Valence   Arousal
00:00:42.000 -0.431208  0.258913
00:00:42.100 -0.276828  0.258345
00:00:42.200 -0.126044  0.257805
00:00:42.300  0.012774  0.257292
00:00:42.400  0.132797  0.256804
00:00:42.500  0.236716  0.256341

In [40]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 50%, Happy - 18-46%, Angry - 61-22%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:42.000,0.502243,0.181685,0.000275,0.612893,0.003011,0.000579,0.002119
00:00:42.100,0.535251,0.241092,0.000246,0.517920,0.004662,0.000863,0.002023
00:00:42.200,0.544003,0.302449,0.000221,0.428494,0.006192,0.001107,0.001881
00:00:42.300,0.536196,0.361938,0.000196,0.349164,0.007338,0.001198,0.001740
00:00:42.400,0.522931,0.414101,0.000175,0.281304,0.008044,0.001221,0.001633
00:00:42.500,0.502529,0.461604,0.000155,0.224888,0.008423,0.001205,0.001563

In [41]:
nn_test.predict() # Более-менее. Neutral - 50-70% - err - 1-20%, Happy - 5-30% - err - 13-16%, 
# Angry - 35-0% - err - 26-21%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:42.000,0.467798,0.000018,0.082064,0.310133,0.025818,0.012844,0.106015
00:00:42.100,0.668899,0.000272,0.071099,0.239416,0.029220,0.011621,0.052538
00:00:42.200,0.819942,0.003750,0.061711,0.181839,0.032964,0.010537,0.025713
00:00:42.300,0.840593,0.068255,0.010583,0.027973,0.031819,0.007115,0.003831
00:00:42.400,0.783831,0.189206,0.002321,0.006042,0.029761,0.005546,0.000885
00:00:42.500,0.688215,0.280971,0.000633,0.001705,0.027738,0.004614,0.000266

In [42]:
df_x = nn_test.get_df_xy('00:00:42.500', '00:00:43.000')
df_x

               Valence   Arousal
00:00:42.500  0.236716  0.256341
00:00:42.600  0.321085  0.255900
00:00:42.700  0.388269  0.255482
00:00:42.800  0.446405  0.255151
00:00:42.900  0.496219  0.255151
00:00:43.000  0.541093  0.258207

In [43]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 50-38%, Happy - 46-61%, Angry - 22-7%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:42.500,0.502529,0.461604,0.000155,0.224888,0.008423,0.001205,0.001563
00:00:42.600,0.478964,0.499737,0.000136,0.178652,0.008664,0.001159,0.001451
00:00:42.700,0.460155,0.529674,0.000120,0.141405,0.008811,0.001105,0.001370
00:00:42.800,0.436789,0.558047,0.000108,0.111643,0.008762,0.001038,0.001290
00:00:42.900,0.412718,0.584249,0.000096,0.088029,0.008597,0.000969,0.001202
00:00:43.000,0.387863,0.610635,0.000088,0.069542,0.008211,0.000915,0.001102

In [44]:
nn_test.predict() # Более-менее. Neutral - 70-40% - err - 20-2%, Happy - 30-62% - err - 16-1%, 
# Angry - 0% - err - 22-7%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:42.500,0.688215,0.280971,0.000633,0.001705,0.027738,0.004614,0.000266
00:00:42.600,0.596057,0.372553,0.000220,0.000609,0.026189,0.003973,0.000101
00:00:42.700,0.517148,0.453065,0.000095,0.000269,0.025010,0.003526,0.000046
00:00:42.800,0.447992,0.524961,0.000046,0.000132,0.024035,0.003181,0.000024
00:00:42.900,0.389947,0.586038,0.000025,0.000072,0.023250,0.002912,0.000013
00:00:43.000,0.337621,0.640709,0.000014,0.000041,0.022789,0.002693,0.000008

In [45]:
df_x = nn_test.get_df_xy('00:00:47.000', '00:00:48.000')
df_x

               Valence   Arousal
00:00:47.000  0.402050  0.299550
00:00:47.100  0.402333  0.299550
00:00:47.200  0.403500  0.299481
00:00:47.300  0.406274  0.299384
00:00:47.400  0.406193  0.299230
00:00:47.500  0.415290  0.299125
00:00:47.600  0.418139  0.298942
00:00:47.700  0.423579  0.298760
00:00:47.800  0.431206  0.298555
00:00:47.900  0.440355  0.298336
00:00:48.000  0.450727  0.298102

In [46]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 71-69%, Happy - 40-45%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:47.000,0.710237,0.407821,0.000096,0.005771,0.004438,0.000165,0.000185
00:00:47.100,0.711148,0.408063,0.000100,0.005730,0.004281,0.000168,0.000181
00:00:47.200,0.713677,0.409234,0.000102,0.005734,0.004085,0.000167,0.000180
00:00:47.300,0.714254,0.412195,0.000105,0.005921,0.003882,0.000161,0.000175
00:00:47.400,0.716460,0.412444,0.000108,0.006251,0.003699,0.000162,0.000173
00:00:47.500,0.713320,0.421777,0.000107,0.006487,0.003612,0.000162,0.000170
00:00:47.600,0.714224,0.424814,0.000107,0.006675,0.003599,0.000168,0.000171
00:00:47.700,0.710022,0.430272,0.000107,0.006693,0.003646,0.000182,0.000167
00:00:47.800,0.706393,0.437887,0.000105,0.006681,0.003628,0.000192,0.000165
00:00:47.900,0.701044,0.447169,0.000104,0.006814,0.003610,0.000197,0.000161
00:00:48.000,0.692921,0.457616,0.000106,0.006888,0.003541,0.000198,0.000157

In [47]:
nn_test.predict() # Плоховато на Neutral (Сойдёт). Neutral - 53-48% - err - 19%, Happy - 48-53% - err - 8%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:47.000,0.459937,0.497891,0.000056,0.000166,0.028574,0.003512,0.000026
00:00:47.100,0.459601,0.498242,0.000056,0.000165,0.028568,0.003510,0.000026
00:00:47.200,0.458274,0.499650,0.000055,0.000163,0.028540,0.003503,0.000026
00:00:47.300,0.455065,0.503036,0.000053,0.000158,0.028479,0.003485,0.000025
00:00:47.400,0.455303,0.502838,0.000054,0.000158,0.028466,0.003486,0.000025
00:00:47.500,0.444609,0.514076,0.000048,0.000141,0.028285,0.003430,0.000023
00:00:47.600,0.441407,0.517498,0.000046,0.000137,0.028215,0.003412,0.000022
00:00:47.700,0.435153,0.524135,0.000043,0.000128,0.028097,0.003379,0.000021
00:00:47.800,0.426377,0.533453,0.000039,0.000117,0.027937,0.003333,0.000019
00:00:47.900,0.415885,0.544619,0.000035,0.000105,0.027748,0.003279,0.000017
00:00:48.000,0.404071,0.557231,0.000031,0.000092,0.027537,0.003219,0.000015

In [48]:
df_x = nn_test.get_df_xy('00:01:06.000', '00:01:07.000') 
df_x

               Valence   Arousal
00:01:06.000 -0.103109  0.283163
00:01:06.100 -0.092284  0.282977
00:01:06.200 -0.085587  0.282701
00:01:06.300 -0.081722  0.282360
00:01:06.400 -0.070623  0.281872
00:01:06.500 -0.059186  0.281336
00:01:06.600 -0.049184  0.280761
00:01:06.700 -0.035158  0.280176
00:01:06.800 -0.022642  0.279583
00:01:06.900 -0.008292  0.278953
00:01:07.000 -0.001789  0.278458

In [49]:
df_y = nn_test.get_df_xy(xy = 'y') # Удивление (Neutral + Happy)
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:06.000,0.735105,0.152540,0.000869,0.255649,0.001597,0.000651,0.000894
00:01:06.100,0.734141,0.157158,0.000902,0.249441,0.001582,0.000660,0.000887
00:01:06.200,0.734078,0.159937,0.000916,0.245525,0.001590,0.000643,0.000889
00:01:06.300,0.734819,0.161817,0.000917,0.243539,0.001637,0.000628,0.000900
00:01:06.400,0.744191,0.165657,0.000897,0.236280,0.001662,0.000610,0.000898
00:01:06.500,0.753816,0.168743,0.000880,0.227929,0.001680,0.000600,0.000896
00:01:06.600,0.764034,0.169269,0.000862,0.218453,0.001695,0.000586,0.000879
00:01:06.700,0.775219,0.172246,0.000826,0.207403,0.001711,0.000575,0.000872
00:01:06.800,0.785698,0.174468,0.000797,0.197109,0.001756,0.000571,0.000872
00:01:06.900,0.793438,0.177854,0.000771,0.186146,0.001756,0.000576,0.000882
00:01:07.000,0.796028,0.178233,0.000745,0.180022,0.001700,0.000569,0.000939

In [50]:
nn_test.predict() # Средненько (Сойдёт)! Neutral - err 4-12%, Happy - err 11-15%, ANGRY - err 6-14%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:06.000,0.799154,0.005363,0.038870,0.120940,0.035413,0.010134,0.015434
00:01:06.100,0.801086,0.006757,0.033921,0.104994,0.035298,0.009826,0.013318
00:01:06.200,0.802437,0.007800,0.031208,0.096167,0.035210,0.009639,0.012172
00:01:06.300,0.803397,0.008481,0.029778,0.091468,0.035140,0.009530,0.011572
00:01:06.400,0.805643,0.010755,0.025923,0.078894,0.034991,0.009231,0.009967
00:01:06.500,0.807971,0.013732,0.022465,0.067620,0.034835,0.008931,0.008546
00:01:06.600,0.810092,0.017000,0.019830,0.059039,0.034688,0.008677,0.007475
00:01:06.700,0.812824,0.022878,0.016610,0.048654,0.034506,0.008333,0.006184
00:01:06.800,0.815303,0.029779,0.014182,0.040888,0.034337,0.008038,0.005223
00:01:06.900,0.818067,0.040170,0.011822,0.033435,0.034150,0.007712,0.004301
00:01:07.000,0.819507,0.045999,0.010902,0.030542,0.034044,0.007567,0.003945

In [51]:
df_x = nn_test.get_df_xy('00:01:25.000', '00:01:26.000')
df_x

               Valence   Arousal
00:01:25.000  0.780514  0.429943
00:01:25.100  0.770180  0.429943
00:01:25.200  0.763402  0.429846
00:01:25.300  0.759536  0.429766
00:01:25.400  0.746653  0.429272
00:01:25.500  0.735193  0.428437
00:01:25.600  0.723706  0.427788
00:01:25.700  0.711666  0.427098
00:01:25.800  0.700324  0.426254
00:01:25.900  0.687633  0.425157
00:01:26.000  0.678700  0.423820

In [52]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 17-31, Happy 78-68
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:25.000,0.170274,0.782413,0.000291,0.001899,0.000740,0.000223,0.000262
00:01:25.100,0.184500,0.772122,0.000297,0.001941,0.000743,0.000216,0.000269
00:01:25.200,0.192932,0.765428,0.000299,0.002026,0.000752,0.000217,0.000271
00:01:25.300,0.197078,0.761560,0.000346,0.002024,0.000750,0.000216,0.000280
00:01:25.400,0.213567,0.748624,0.000404,0.001971,0.000785,0.000210,0.000304
00:01:25.500,0.234013,0.737090,0.000432,0.001897,0.000816,0.000200,0.000325
00:01:25.600,0.253310,0.725588,0.000472,0.001882,0.000829,0.000195,0.000335
00:01:25.700,0.271598,0.713548,0.000502,0.001882,0.000841,0.000194,0.000344
00:01:25.800,0.284844,0.702225,0.000512,0.001901,0.000863,0.000196,0.000349
00:01:25.900,0.300856,0.689563,0.000540,0.001930,0.000882,0.000197,0.000374
00:01:26.000,0.319784,0.680661,0.000564,0.001960,0.000893,0.000195,0.000386

In [53]:
nn_test.predict() # Neutral - 17-24% - err 0-7%, Happy 84-77% - err 6-1% - Здорово!

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:25.000,0.078909,0.900495,1.719543e-07,6.368928e-07,0.033835,0.001906,9.650847e-08
00:01:25.100,0.082585,0.895796,1.957924e-07,7.228155e-07,0.034067,0.001941,1.087984e-07
00:01:25.200,0.085108,0.892584,2.133617e-07,7.859238e-07,0.034209,0.001965,1.178046e-07
00:01:25.300,0.086585,0.890707,2.241242e-07,8.245024e-07,0.034287,0.001978,1.232999e-07
00:01:25.400,0.091747,0.884186,2.645363e-07,9.688089e-07,0.034525,0.002023,1.438330e-07
00:01:25.500,0.096697,0.877996,3.075357e-07,1.121425e-06,0.034694,0.002064,1.655634e-07
00:01:25.600,0.101833,0.871562,3.571156e-07,1.296788e-06,0.034885,0.002106,1.903064e-07
00:01:25.700,0.107478,0.864506,4.177191e-07,1.510217e-06,0.035085,0.002151,2.202399e-07
00:01:25.800,0.113118,0.857503,4.849335e-07,1.745708e-06,0.035252,0.002194,2.531889e-07
00:01:25.900,0.119793,0.849263,5.737376e-07,2.055237e-06,0.035424,0.002243,2.963547e-07
00:01:26.000,0.124922,0.843042,6.487314e-07,2.314735e-06,0.035480,0.002277,3.328239e-07

In [54]:
df_x = nn_test.get_df_xy('00:01:38.000', '00:01:39.000')
df_x

               Valence   Arousal
00:01:38.000  0.724162  0.396821
00:01:38.100  0.725256  0.395991
00:01:38.200  0.725922  0.395153
00:01:38.300  0.732286  0.394256
00:01:38.400  0.728995  0.393182
00:01:38.500  0.722660  0.391859
00:01:38.600  0.718987  0.390558
00:01:38.700  0.718649  0.389392
00:01:38.800  0.717313  0.388218
00:01:38.900  0.715846  0.386973
00:01:39.000  0.716951  0.385782

In [55]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 24-28, Happy 72-71
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:38.000,0.247921,0.727225,0.000302,0.002924,0.002745,0.003063,0.000617
00:01:38.100,0.245379,0.728168,0.000297,0.002864,0.002651,0.002912,0.000596
00:01:38.200,0.248069,0.728863,0.000286,0.002826,0.002657,0.002941,0.000590
00:01:38.300,0.249211,0.735282,0.000272,0.002743,0.002670,0.002996,0.000580
00:01:38.400,0.262386,0.731932,0.000260,0.002584,0.002722,0.002937,0.000555
00:01:38.500,0.279061,0.725456,0.000248,0.002368,0.002732,0.002796,0.000528
00:01:38.600,0.286941,0.721679,0.000234,0.002201,0.002678,0.002692,0.000514
00:01:38.700,0.286773,0.721287,0.000228,0.002108,0.002710,0.002639,0.000534
00:01:38.800,0.286524,0.719876,0.000228,0.002073,0.002824,0.002564,0.000535
00:01:38.900,0.286901,0.718372,0.000235,0.002071,0.002820,0.002526,0.000525
00:01:39.000,0.282643,0.719507,0.000245,0.002121,0.002750,0.002556,0.000521

In [56]:
nn_test.predict() # Нормас

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:38.000,0.112591,0.862815,4.540832e-07,0.000002,0.031575,0.002075,2.525200e-07
00:01:38.100,0.112374,0.863210,4.508444e-07,0.000002,0.031468,0.002070,2.512680e-07
00:01:38.200,0.112365,0.863352,4.500707e-07,0.000002,0.031370,0.002066,2.512843e-07
00:01:38.300,0.109683,0.866780,4.184596e-07,0.000001,0.031148,0.002043,2.353606e-07
00:01:38.400,0.111626,0.864562,4.398613e-07,0.000002,0.031108,0.002053,2.469755e-07
00:01:38.500,0.115171,0.860430,4.813309e-07,0.000002,0.031106,0.002075,2.690993e-07
00:01:38.600,0.117475,0.857822,5.092951e-07,0.000002,0.031052,0.002088,2.842307e-07
00:01:38.700,0.118093,0.857257,5.162267e-07,0.000002,0.030942,0.002088,2.884628e-07
00:01:38.800,0.119217,0.856077,5.298812e-07,0.000002,0.030853,0.002092,2.961852e-07
00:01:38.900,0.120445,0.854786,5.450990e-07,0.000002,0.030760,0.002096,3.047772e-07
00:01:39.000,0.120351,0.855094,5.426933e-07,0.000002,0.030620,0.002091,3.042483e-07

In [57]:
v = 3
dir_model = 'saved_models'
layer = 'first'
path_dir_model = os.path.join(project_dir_path, dir_model, layer, f'_{v}')
print(path_dir_model)
saved_models = list(os.walk(path_dir_model))[0]
save_name = f'model_{layer}_{N}_{v}'
path = os.path.join(path_dir_model, save_name)
path

/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_3

'/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_3/model_first_6_3'

In [58]:
model.save(path)

2024-03-16 22:47:18.091096: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.

INFO:tensorflow:Assets written to: /home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_3/model_first_6_3/assets

In [59]:
from tensorflow.keras.models import load_model

In [60]:
model = load_model(path)

In [61]:
nn = NeuralNetwork(pa_vector_test, seven_vector_test, model)

/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/lib/nn_train/neural_network.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df_x[field] = self.df_x[field].apply(lambda entry: float(entry))
/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/lib/nn_train/neural_network.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df_y[field] = self.df_y[field].apply(lambda entry: float(entry))

In [62]:
#Last test

In [63]:
df_x = nn.get_df_xy('00:01:38.000', '00:01:39.000')
df_x

               Valence   Arousal
00:01:38.000  0.724162  0.396821
00:01:38.100  0.725256  0.395991
00:01:38.200  0.725922  0.395153
00:01:38.300  0.732286  0.394256
00:01:38.400  0.728995  0.393182
00:01:38.500  0.722660  0.391859
00:01:38.600  0.718987  0.390558
00:01:38.700  0.718649  0.389392
00:01:38.800  0.717313  0.388218
00:01:38.900  0.715846  0.386973
00:01:39.000  0.716951  0.385782

In [64]:
df_y = nn.get_df_xy(xy = 'y') # Neutral - 24-28, Happy 72-71
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:38.000,0.247921,0.727225,0.000302,0.002924,0.002745,0.003063,0.000617
00:01:38.100,0.245379,0.728168,0.000297,0.002864,0.002651,0.002912,0.000596
00:01:38.200,0.248069,0.728863,0.000286,0.002826,0.002657,0.002941,0.000590
00:01:38.300,0.249211,0.735282,0.000272,0.002743,0.002670,0.002996,0.000580
00:01:38.400,0.262386,0.731932,0.000260,0.002584,0.002722,0.002937,0.000555
00:01:38.500,0.279061,0.725456,0.000248,0.002368,0.002732,0.002796,0.000528
00:01:38.600,0.286941,0.721679,0.000234,0.002201,0.002678,0.002692,0.000514
00:01:38.700,0.286773,0.721287,0.000228,0.002108,0.002710,0.002639,0.000534
00:01:38.800,0.286524,0.719876,0.000228,0.002073,0.002824,0.002564,0.000535
00:01:38.900,0.286901,0.718372,0.000235,0.002071,0.002820,0.002526,0.000525
00:01:39.000,0.282643,0.719507,0.000245,0.002121,0.002750,0.002556,0.000521

In [65]:
nn.predict() # Neutral - err 5-1%, Happy 3% - НОРМ!

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:38.000,0.112591,0.862815,4.540832e-07,0.000002,0.031575,0.002075,2.525200e-07
00:01:38.100,0.112374,0.863210,4.508444e-07,0.000002,0.031468,0.002070,2.512680e-07
00:01:38.200,0.112365,0.863352,4.500707e-07,0.000002,0.031370,0.002066,2.512843e-07
00:01:38.300,0.109683,0.866780,4.184596e-07,0.000001,0.031148,0.002043,2.353606e-07
00:01:38.400,0.111626,0.864562,4.398613e-07,0.000002,0.031108,0.002053,2.469755e-07
00:01:38.500,0.115171,0.860430,4.813309e-07,0.000002,0.031106,0.002075,2.690993e-07
00:01:38.600,0.117475,0.857822,5.092951e-07,0.000002,0.031052,0.002088,2.842307e-07
00:01:38.700,0.118093,0.857257,5.162267e-07,0.000002,0.030942,0.002088,2.884628e-07
00:01:38.800,0.119217,0.856077,5.298812e-07,0.000002,0.030853,0.002092,2.961852e-07
00:01:38.900,0.120445,0.854786,5.450990e-07,0.000002,0.030760,0.002096,3.047772e-07
00:01:39.000,0.120351,0.855094,5.426933e-07,0.000002,0.030620,0.002091,3.042483e-07