In [80]:
import os
from tensorflow.keras.models import load_model

In [81]:
N = 6

project_dir_path = os.environ["NIR_1_sem_magistracy"]
# код с моделями layer взят из NeuralNetwork_11_first_layer_tests
dir_model = 'saved_models'
layer = 'first'
path_dir_model = os.path.join(project_dir_path, dir_model, layer, '_1')
print(path_dir_model)
saved_models = list(os.walk(path_dir_model))[0]
save_name = f'model_{layer}_{N}'
path = os.path.join(path_dir_model, save_name)
path

/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_1

'/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_1/model_first_6'

In [82]:
model = load_model(path)
model

In [83]:
#Test on Aleksashina 1 - Bad result in '00:00:35.000', '00:00:37.000'

In [84]:
data_dir = 'Data'
data_dir = os.path.join(project_dir_path, data_dir)
csv_file = "Participant 1_Aleksashina_Analysis 1_video_20190607_114857_detailed.csv"
csv_path = os.path.join(data_dir, csv_file)
csv_path

'/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/Data/Participant 1_Aleksashina_Analysis 1_video_20190607_114857_detailed.csv'

In [85]:
import pandas as pd

In [86]:
df_test = pd.read_csv(csv_path, sep='\t', skiprows = lambda i: i in range(8))

In [87]:
df_first = df_test.columns[0]
df_test.columns = df_test.columns[1:].insert(-2, 'UNKNOWN')
df_test.insert(0, df_first, df_test.index)
df_test

,Video Time,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted,Valence,Arousal,...,Action Unit 12 - Right - Lip Corner Puller,Action Unit 14 - Right - Dimpler,Action Unit 15 - Right - Lip Corner Depressor,Action Unit 20 - Right - Lip Stretcher,Action Unit 43 - Right - Eyes Closed,Stimulus,Event Marker,UNKNOWN,Participant Name,Analysis Index
00:00:00.000,00:00:00.000,0.973121,0.019527,0.000404,0.043879,0.004099,0.000322,0.001946,-0.024352,0.255187,...,0.0,0.017570,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:00:00.100,00:00:00.100,0.974289,0.020129,0.000382,0.042413,0.004014,0.000298,0.001820,-0.022284,0.260074,...,0.0,0.032680,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:00:00.200,00:00:00.200,0.975457,0.020731,0.000361,0.040947,0.003930,0.000273,0.001693,-0.020216,0.264960,...,0.0,0.047791,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:00:00.300,00:00:00.300,0.975028,0.020480,0.000345,0.042622,0.003916,0.000256,0.001549,-0.022143,0.269347,...,0.0,0.060645,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:00:00.400,00:00:00.400,0.974542,0.020394,0.000326,0.044417,0.003831,0.000235,0.001438,-0.024022,0.273202,...,0.0,0.068510,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
00:01:50.900,00:01:50.900,0.969587,0.016939,0.000846,0.051552,0.004851,0.000162,0.000609,-0.034614,0.317045,...,0.0,0.199020,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:01:51.000,00:01:51.000,0.969071,0.017130,0.000856,0.052158,0.004848,0.000168,0.000615,-0.035027,0.316651,...,0.0,0.202110,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:01:51.100,00:01:51.100,0.968842,0.017460,0.000885,0.052096,0.004807,0.000172,0.000620,-0.034636,0.316144,...,0.0,0.196561,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:01:51.200,00:01:51.200,0.968608,0.018322,0.000899,0.052130,0.004756,0.000176,0.000617,-0.033808,0.315641,...,0.0,0.196161,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1
00:01:51.300,00:01:51.300,0.968453,0.019037,0.000889,0.052191,0.004726,0.000178,0.000603,-0.033154,0.315094,...,0.0,0.193525,0.0,0.0,0.0,No Stimulus,No Event Marker,UNKNOWN,Aleksashina,Analysis 1

In [88]:
seven_fields = [
    'Neutral', 
    'Happy', 
    'Sad', 
    'Angry', 
    'Surprised', 
    'Scared', 
    'Disgusted'
]

In [89]:
seven_vector_test = df_test[seven_fields]
seven_vector_test

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:00.000,0.973121,0.019527,0.000404,0.043879,0.004099,0.000322,0.001946
00:00:00.100,0.974289,0.020129,0.000382,0.042413,0.004014,0.000298,0.001820
00:00:00.200,0.975457,0.020731,0.000361,0.040947,0.003930,0.000273,0.001693
00:00:00.300,0.975028,0.020480,0.000345,0.042622,0.003916,0.000256,0.001549
00:00:00.400,0.974542,0.020394,0.000326,0.044417,0.003831,0.000235,0.001438
...,...,...,...,...,...,...,...
00:01:50.900,0.969587,0.016939,0.000846,0.051552,0.004851,0.000162,0.000609
00:01:51.000,0.969071,0.017130,0.000856,0.052158,0.004848,0.000168,0.000615
00:01:51.100,0.968842,0.017460,0.000885,0.052096,0.004807,0.000172,0.000620
00:01:51.200,0.968608,0.018322,0.000899,0.052130,0.004756,0.000176,0.000617
00:01:51.300,0.968453,0.019037,0.000889,0.052191,0.004726,0.000178,0.000603

In [90]:
pa_fields =     [
    'Valence',
    'Arousal'
]

In [91]:
pa_vector_test = df_test[pa_fields]
pa_vector_test

               Valence   Arousal
00:00:00.000 -0.024352  0.255187
00:00:00.100 -0.022284  0.260074
00:00:00.200 -0.020216  0.264960
00:00:00.300 -0.022143  0.269347
00:00:00.400 -0.024022  0.273202
...                ...       ...
00:01:50.900 -0.034614  0.317045
00:01:51.000 -0.035027  0.316651
00:01:51.100 -0.034636  0.316144
00:01:51.200 -0.033808  0.315641
00:01:51.300 -0.033154  0.315094

[1114 rows x 2 columns]

In [92]:
import sys

lib_dir = 'lib'
lib_dir_path = os.path.join(project_dir_path, lib_dir)
sys.path.append(lib_dir_path)
from nn_train.neural_network import NeuralNetwork

In [93]:
nn_test = NeuralNetwork(pa_vector_test, seven_vector_test, model)

/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/lib/nn_train/neural_network.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df_x[field] = self.df_x[field].apply(lambda entry: float(entry))
/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/lib/nn_train/neural_network.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df_y[field] = self.df_y[field].apply(lambda entry: float(entry))

In [94]:
df_x = nn_test.get_df_xy('00:00:00.000', '00:00:00.100')
df_x

               Valence   Arousal
00:00:00.000 -0.024352  0.255187
00:00:00.100 -0.022284  0.260074

In [95]:
df_y = nn_test.get_df_xy(xy = 'y')
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:00.000,0.973121,0.019527,0.000404,0.043879,0.004099,0.000322,0.001946
00:00:00.100,0.974289,0.020129,0.000382,0.042413,0.004014,0.000298,0.001820

In [96]:
nn_test.predict()

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:00.000,0.920732,0.029927,0.028238,0.041578,0.031127,0.007209,0.010298
00:00:00.100,0.918784,0.030464,0.026586,0.039276,0.031593,0.007202,0.009638

In [97]:
df_x = nn_test.get_df_xy('00:00:35.000', '00:00:36.000')
df_x

               Valence   Arousal
00:00:35.000 -0.352308  0.269101
00:00:35.100 -0.350539  0.268026
00:00:35.200 -0.326232  0.267004
00:00:35.300 -0.285224  0.266032
00:00:35.400 -0.242059  0.265109
00:00:35.500 -0.200804  0.264233
00:00:35.600 -0.170360  0.263399
00:00:35.700 -0.190755  0.262607
00:00:35.800 -0.212631  0.261855
00:00:35.900 -0.218393  0.261140
00:00:36.000 -0.214707  0.260461

In [98]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 18-19%, Happy - 33-44%, Angry - 68-66%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:35.000,0.182593,0.330956,0.000412,0.683264,0.000224,0.000154,0.001101
00:00:35.100,0.182888,0.332008,0.000402,0.682547,0.000225,0.000146,0.001114
00:00:35.200,0.189628,0.342300,0.000385,0.668532,0.000222,0.000136,0.001137
00:00:35.300,0.197984,0.366362,0.000355,0.651586,0.000214,0.000128,0.001147
00:00:35.400,0.204422,0.397417,0.000318,0.639476,0.000206,0.000125,0.001140
00:00:35.500,0.210753,0.425377,0.000289,0.626181,0.000202,0.000124,0.001132
00:00:35.600,0.214195,0.446865,0.000269,0.617225,0.000197,0.000127,0.001100
00:00:35.700,0.205753,0.439168,0.000253,0.629923,0.000196,0.000130,0.001036
00:00:35.800,0.197402,0.431040,0.000236,0.643670,0.000188,0.000138,0.000979
00:00:35.900,0.192098,0.436435,0.000215,0.654827,0.000177,0.000149,0.000936
00:00:36.000,0.189787,0.446914,0.000195,0.661620,0.000168,0.000154,0.000912

In [99]:
nn_test.predict() # Ошибки на 40-50%!

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:35.000,0.739434,0.000077,0.082791,0.169093,0.025234,0.009848,0.085285
00:00:35.100,0.741800,0.000081,0.082655,0.168339,0.025180,0.009818,0.084807
00:00:35.200,0.765159,0.000123,0.080868,0.161243,0.025698,0.009695,0.076100
00:00:35.300,0.800765,0.000250,0.077934,0.149977,0.026668,0.009507,0.063143
00:00:35.400,0.833649,0.000528,0.074952,0.138847,0.027738,0.009315,0.051735
00:00:35.500,0.860874,0.001077,0.072201,0.128865,0.028800,0.009136,0.042675
00:00:35.600,0.878548,0.001826,0.070229,0.121865,0.029589,0.009002,0.036999
00:00:35.700,0.867425,0.001295,0.071540,0.126276,0.028917,0.009065,0.040844
00:00:35.800,0.854508,0.000896,0.072970,0.131177,0.028223,0.009135,0.045382
00:00:35.900,0.851144,0.000816,0.073350,0.132399,0.027991,0.009144,0.046711
00:00:36.000,0.853751,0.000873,0.073103,0.131406,0.028024,0.009116,0.045978

In [100]:
df_x = nn_test.get_df_xy('00:00:36.000', '00:00:38.000')
df_x

               Valence   Arousal
00:00:36.000 -0.214707  0.260461
00:00:36.100 -0.215263  0.259816
00:00:36.200 -0.183632  0.259228
00:00:36.300 -0.147168  0.258936
00:00:36.400 -0.117836  0.258876
00:00:36.500 -0.091053  0.258876
00:00:36.600 -0.067193  0.262077
00:00:36.700 -0.040169  0.265263
00:00:36.800 -0.026193  0.267305
00:00:36.900 -0.011659  0.269329
00:00:37.000  0.001245  0.270993
00:00:37.100  0.017058  0.272699
00:00:37.200  0.035471  0.274351
00:00:37.300  0.045651  0.274641
00:00:37.400  0.037331  0.274641
00:00:37.500  0.019146  0.274552
00:00:37.600  0.002470  0.274409
00:00:37.700 -0.014269  0.274178
00:00:37.800 -0.012094  0.273958
00:00:37.900  0.001319  0.273736
00:00:38.000  0.015823  0.273556

In [101]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 19-23%, Happy - 44-56%, Angry - 66-55%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:36.000,0.189787,0.446914,0.000195,0.661620,0.000168,0.000154,0.000912
00:00:36.100,0.184945,0.455178,0.000176,0.670441,0.000158,0.000153,0.000907
00:00:36.200,0.189195,0.478034,0.000159,0.661666,0.000151,0.000145,0.000883
00:00:36.300,0.196710,0.498410,0.000149,0.645577,0.000148,0.000137,0.000835
00:00:36.400,0.201433,0.516213,0.000143,0.634049,0.000147,0.000128,0.000784
00:00:36.500,0.206537,0.530494,0.000139,0.621547,0.000150,0.000119,0.000746
00:00:36.600,0.213259,0.539001,0.000133,0.606194,0.000154,0.000111,0.000718
00:00:36.700,0.216637,0.549414,0.000127,0.589583,0.000160,0.000107,0.000705
00:00:36.800,0.218805,0.557725,0.000121,0.583918,0.000159,0.000102,0.000706
00:00:36.900,0.219156,0.565864,0.000115,0.577523,0.000164,0.000101,0.000695
00:00:37.000,0.220346,0.569772,0.000110,0.568527,0.000171,0.000101,0.000689
00:00:37.100,0.220652,0.573952,0.000107,0.556894,0.000178,0.000100,0.000688
00:00:37.200,0.220773,0.578310,0.000104,0.542839,0.000185,0.000100,0.000695
00:00:37.300,0.221660,0.581433,0.000102,0.535782,0.000194,0.000115,0.000711
00:00:37.400,0.228033,0.572191,0.000100,0.534860,0.000205,0.000127,0.000716
00:00:37.500,0.229366,0.564783,0.000102,0.545637,0.000208,0.000134,0.000733
00:00:37.600,0.227043,0.561071,0.000104,0.558601,0.000207,0.000137,0.000757
00:00:37.700,0.225937,0.553081,0.000104,0.567351,0.000206,0.000137,0.000822
00:00:37.800,0.227376,0.557128,0.000104,0.569222,0.000204,0.000138,0.000881
00:00:37.900,0.228799,0.561518,0.000105,0.560199,0.000205,0.000137,0.000959
00:00:38.000,0.229891,0.565980,0.000106,0.550158,0.000208,0.000136,0.000998

In [102]:
nn_test.predict() # Ошибки на 40-70%!!!

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:36.000,0.853751,0.000873,0.073103,0.131406,0.028024,0.009116,0.045978
00:00:36.100,0.853655,0.000869,0.073137,0.131418,0.027944,0.009105,0.046168
00:00:36.200,0.872690,0.001501,0.071067,0.124077,0.028769,0.008972,0.039799
00:00:36.300,0.891853,0.002806,0.068748,0.116117,0.029791,0.008828,0.033470
00:00:36.400,0.905334,0.004633,0.066935,0.110068,0.030658,0.008717,0.029084
00:00:36.500,0.914925,0.007430,0.062341,0.100003,0.031354,0.008543,0.024659
00:00:36.600,0.915045,0.011993,0.045665,0.071695,0.031702,0.008072,0.017449
00:00:36.700,0.915376,0.020603,0.032015,0.048788,0.032057,0.007566,0.011804
00:00:36.800,0.915371,0.027141,0.026523,0.039760,0.032281,0.007319,0.009607
00:00:36.900,0.915411,0.036088,0.021801,0.032097,0.032506,0.007070,0.007757
00:00:37.000,0.915505,0.046387,0.018322,0.026528,0.032694,0.006856,0.006421
00:00:37.100,0.915768,0.062932,0.014830,0.021016,0.032892,0.006600,0.005104
00:00:37.200,0.910049,0.072378,0.011731,0.016571,0.032963,0.006417,0.004051
00:00:37.300,0.905990,0.075797,0.010365,0.014656,0.032920,0.006331,0.003602
00:00:37.400,0.909255,0.073025,0.011449,0.016177,0.032979,0.006402,0.003957
00:00:37.500,0.915078,0.064983,0.014254,0.020182,0.033080,0.006576,0.004889
00:00:37.600,0.914052,0.046750,0.017607,0.025556,0.033034,0.006855,0.006147
00:00:37.700,0.913051,0.033422,0.021763,0.032359,0.032979,0.007147,0.007739
00:00:37.800,0.913296,0.034964,0.021210,0.031431,0.032961,0.007107,0.007526
00:00:37.900,0.914281,0.045838,0.017950,0.026076,0.032965,0.006871,0.006278
00:00:38.000,0.915307,0.061171,0.014971,0.021278,0.032974,0.006625,0.005156

In [103]:
model

In [104]:
#Будем дообучаться с '00:00:30.000' до '00:00:47.000'

In [105]:
df_x = nn_test.get_df_xy('00:00:30.000', '00:00:47.000')
df_x

               Valence   Arousal
00:00:30.000  0.725731  0.339765
00:00:30.100  0.737862  0.339765
00:00:30.200  0.726528  0.339271
00:00:30.300  0.712153  0.338363
00:00:30.400  0.709858  0.337356
...                ...       ...
00:00:46.600  0.405003  0.296618
00:00:46.700  0.410025  0.298988
00:00:46.800  0.410327  0.299550
00:00:46.900  0.404849  0.299550
00:00:47.000  0.402050  0.299550

[171 rows x 2 columns]

In [106]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 19-23%, Happy - 44-56%, Angry - 66-55%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:30.000,0.132133,0.756668,0.001669,0.030937,0.000408,0.000671,0.001260
00:00:30.100,0.130447,0.768046,0.001361,0.030184,0.000499,0.000711,0.001268
00:00:30.200,0.147706,0.755921,0.001117,0.029393,0.000589,0.000680,0.001202
00:00:30.300,0.164955,0.739512,0.001299,0.027358,0.000643,0.000609,0.001229
00:00:30.400,0.171592,0.735537,0.001367,0.025679,0.000635,0.000525,0.001322
...,...,...,...,...,...,...,...
00:00:46.600,0.700990,0.412003,0.000073,0.007000,0.005182,0.000170,0.000179
00:00:46.700,0.698069,0.416607,0.000076,0.006581,0.005014,0.000168,0.000171
00:00:46.800,0.700179,0.416593,0.000081,0.006266,0.004808,0.000166,0.000175
00:00:46.900,0.706128,0.410886,0.000090,0.006037,0.004576,0.000164,0.000182
00:00:47.000,0.710237,0.407821,0.000096,0.005771,0.004438,0.000165,0.000185

In [107]:
nn_test.predict()

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:30.000,0.243694,0.715825,0.000002,0.000003,0.034825,0.002612,9.099173e-07
00:00:30.100,0.233381,0.727609,0.000001,0.000002,0.034733,0.002570,7.930909e-07
00:00:30.200,0.243307,0.716400,0.000002,0.000003,0.034765,0.002609,9.057443e-07
00:00:30.300,0.256479,0.701669,0.000002,0.000003,0.034775,0.002658,1.074626e-06
00:00:30.400,0.259169,0.698901,0.000002,0.000003,0.034683,0.002666,1.112923e-06
...,...,...,...,...,...,...,...
00:00:46.600,0.625041,0.328049,0.000115,0.000167,0.032619,0.003950,5.066975e-05
00:00:46.700,0.617673,0.334519,0.000107,0.000155,0.032826,0.003927,4.686181e-05
00:00:46.800,0.616903,0.335103,0.000106,0.000154,0.032882,0.003926,4.646778e-05
00:00:46.900,0.622945,0.329225,0.000113,0.000164,0.032921,0.003955,4.944272e-05
00:00:47.000,0.626018,0.326242,0.000117,0.000170,0.032941,0.003969,5.103536e-05

In [108]:
len(df_x)

171

In [109]:
import numpy as np

In [110]:
x = []
for i in range(len(df_x)):
    x.append((df_x['Valence'][i], df_x['Arousal'][i])) 
    
x = np.array(x)

In [111]:
x.shape

(171, 2)

In [112]:
y = []
for i in range(len(df_y)):
    y.append(tuple(df_y[col][i] for col in df_y.columns)) 
y = np.array(y)

In [113]:
y.shape

(171, 7)

In [114]:
model.fit(x=x, y=y, epochs=5, batch_size=30)

Epoch 1/5
6/6 [==============================] - 3s 18ms/step - loss: 0.0606
Epoch 2/5
6/6 [==============================] - 0s 20ms/step - loss: 0.0591
Epoch 3/5
6/6 [==============================] - 0s 19ms/step - loss: 0.0575
Epoch 4/5
6/6 [==============================] - 0s 21ms/step - loss: 0.0560
Epoch 5/5
6/6 [==============================] - 0s 15ms/step - loss: 0.0545

In [115]:
# Пройдём тест заново

In [116]:
df_x = nn_test.get_df_xy('00:00:00.000', '00:00:00.100')
df_x

               Valence   Arousal
00:00:00.000 -0.024352  0.255187
00:00:00.100 -0.022284  0.260074

In [117]:
df_y = nn_test.get_df_xy(xy = 'y') #Neutral - 97%, Happy - 1-2%, Angry - 4%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:00.000,0.973121,0.019527,0.000404,0.043879,0.004099,0.000322,0.001946
00:00:00.100,0.974289,0.020129,0.000382,0.042413,0.004014,0.000298,0.001820

In [118]:
nn_test.predict() #Neutral - 91% - err - 6%, Happy - 2-3% - err - 1-2%, Angry - 7-8% - err - 3-4% - ХОРОШО.

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:00.000,0.886681,0.030826,0.022563,0.045364,0.031488,0.007547,0.008335
00:00:00.100,0.883879,0.031398,0.021212,0.042862,0.031951,0.007540,0.007793

In [119]:
df_x = nn_test.get_df_xy('00:00:16.000', '00:00:17.000')
df_x

               Valence   Arousal
00:00:16.000  0.982274  0.763761
00:00:16.100  0.982497  0.761543
00:00:16.200  0.982457  0.759395
00:00:16.300  0.982780  0.757186
00:00:16.400  0.983181  0.754926
00:00:16.500  0.983513  0.752694
00:00:16.600  0.983897  0.750396
00:00:16.700  0.983741  0.748033
00:00:16.800  0.982967  0.745634
00:00:16.900  0.982504  0.743361
00:00:17.000  0.982369  0.741136

In [120]:
df_y = nn_test.get_df_xy(xy = 'y') # Happy - 98%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:16.000,0.007980,0.984054,0.000013,0.001780,0.002200,0.001339,0.000060
00:00:16.100,0.007884,0.984246,0.000013,0.001749,0.002323,0.001302,0.000059
00:00:16.200,0.007840,0.984331,0.000013,0.001875,0.002367,0.001226,0.000057
00:00:16.300,0.007679,0.984653,0.000014,0.001873,0.002433,0.001246,0.000056
00:00:16.400,0.007520,0.984970,0.000014,0.001789,0.002598,0.001347,0.000054
00:00:16.500,0.007385,0.985240,0.000014,0.001727,0.002701,0.001379,0.000054
00:00:16.600,0.007240,0.985530,0.000014,0.001633,0.002647,0.001379,0.000053
00:00:16.700,0.007345,0.985320,0.000014,0.001580,0.002596,0.001452,0.000057
00:00:16.800,0.007730,0.984552,0.000013,0.001585,0.002543,0.001457,0.000060
00:00:16.900,0.007821,0.984368,0.000013,0.001865,0.002409,0.001359,0.000064
00:00:17.000,0.007792,0.984427,0.000013,0.002058,0.002319,0.001242,0.000064

In [121]:
nn_test.predict() #Happy - 94% - err - 4% - ХОРОШО.

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:16.000,0.015426,0.972411,1.875750e-09,5.672388e-09,0.102289,0.001914,7.257333e-10
00:00:16.100,0.015527,0.972304,1.903069e-09,5.746778e-09,0.101614,0.001911,7.386764e-10
00:00:16.200,0.015645,0.972165,1.935987e-09,5.837866e-09,0.100975,0.001910,7.536393e-10
00:00:16.300,0.015740,0.972071,1.961615e-09,5.906805e-09,0.100307,0.001907,7.661339e-10
00:00:16.400,0.015833,0.971984,1.986518e-09,5.973230e-09,0.099625,0.001904,7.785269e-10
00:00:16.500,0.015929,0.971889,2.012969e-09,6.044160e-09,0.098958,0.001901,7.915278e-10
00:00:16.600,0.016026,0.971797,2.039516e-09,6.114940e-09,0.098274,0.001899,8.047520e-10
00:00:16.700,0.016168,0.971627,2.081202e-09,6.230066e-09,0.097596,0.001897,8.237482e-10
00:00:16.800,0.016360,0.971369,2.140479e-09,6.396666e-09,0.096934,0.001898,8.494397e-10
00:00:16.900,0.016523,0.971159,2.190959e-09,6.537265e-09,0.096301,0.001897,8.718406e-10
00:00:17.000,0.016660,0.970997,2.232774e-09,6.652140e-09,0.095674,0.001896,8.910852e-10

In [122]:
df_x = nn_test.get_df_xy('00:00:21.000', '00:00:23.000')
df_x

               Valence   Arousal
00:00:21.000  0.964579  0.663201
00:00:21.100  0.943782  0.659207
00:00:21.200  0.871111  0.652940
00:00:21.300  0.762326  0.644623
00:00:21.400  0.640243  0.633058
00:00:21.500  0.520727  0.618742
00:00:21.600  0.413288  0.603645
00:00:21.700  0.323662  0.588063
00:00:21.800  0.251679  0.572172
00:00:21.900  0.194049  0.555099
00:00:22.000  0.148148  0.536985
00:00:22.100  0.111093  0.518199
00:00:22.200  0.080803  0.499630
00:00:22.300  0.054733  0.481918
00:00:22.400  0.034692  0.465653
00:00:22.500  0.019820  0.451096
00:00:22.600  0.007910  0.438177
00:00:22.700 -0.006161  0.426671
00:00:22.800 -0.020030  0.416402
00:00:22.900 -0.035617  0.407217
00:00:23.000 -0.047857  0.399033

In [123]:
df_y = nn_test.get_df_xy(xy = 'y') #Neutral - 1-95%, Happy - 96-1%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:21.000,0.019636,0.966993,0.000121,0.002414,0.002644,0.002096,0.000165
00:00:21.100,0.051523,0.946047,0.000221,0.002265,0.002547,0.002061,0.000355
00:00:21.200,0.135548,0.875374,0.000303,0.004263,0.002576,0.001903,0.000715
00:00:21.300,0.247636,0.770754,0.000351,0.008427,0.002592,0.001688,0.000968
00:00:21.400,0.365667,0.655739,0.000364,0.015496,0.002655,0.001459,0.001092
00:00:21.500,0.477339,0.544180,0.000356,0.023453,0.002761,0.001233,0.001120
00:00:21.600,0.576351,0.443905,0.000341,0.030617,0.002846,0.001026,0.001090
00:00:21.700,0.660592,0.357482,0.000767,0.033820,0.002812,0.000842,0.001407
00:00:21.800,0.730230,0.284993,0.004092,0.033314,0.002743,0.000681,0.002124
00:00:21.900,0.786891,0.225365,0.007646,0.031317,0.002668,0.000547,0.002939
00:00:22.000,0.831870,0.176788,0.012967,0.028640,0.002633,0.000438,0.003709
00:00:22.100,0.867497,0.137732,0.016150,0.026639,0.002577,0.000354,0.004042
00:00:22.200,0.894690,0.106713,0.017925,0.025911,0.002472,0.000289,0.004167
00:00:22.300,0.913525,0.082282,0.019553,0.027548,0.002337,0.000237,0.004469
00:00:22.400,0.927302,0.063380,0.020318,0.028688,0.002183,0.000197,0.004664
00:00:22.500,0.937785,0.048936,0.019899,0.029117,0.002059,0.000164,0.004699
00:00:22.600,0.946148,0.037900,0.018283,0.029990,0.002009,0.000141,0.004482
00:00:22.700,0.950496,0.029679,0.015991,0.035840,0.002078,0.000128,0.004055
00:00:22.800,0.952492,0.023617,0.013573,0.043648,0.002294,0.000120,0.003566
00:00:22.900,0.951661,0.018998,0.011318,0.054615,0.002543,0.000117,0.003085
00:00:23.000,0.950978,0.015523,0.009315,0.063379,0.002740,0.000121,0.002662

In [124]:
nn_test.predict() #Neutral - 7-84% - err - 6-11%, Happy - 93-3% - err - 3% - Допустимо!

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:21.000,0.023591,0.962473,5.081525e-09,1.434386e-08,0.076275,0.001887,2.222526e-09
00:00:21.100,0.026314,0.958220,6.764311e-09,1.898629e-08,0.075982,0.001944,2.923032e-09
00:00:21.200,0.037461,0.940459,1.731484e-08,4.789158e-08,0.076732,0.002164,7.098096e-09
00:00:21.300,0.062737,0.900594,7.012623e-08,1.898820e-07,0.078119,0.002542,2.652862e-08
00:00:21.400,0.110298,0.828481,3.428585e-07,9.051320e-07,0.079168,0.003042,1.188825e-07
00:00:21.500,0.186345,0.721582,1.659342e-06,4.264805e-06,0.079486,0.003622,5.304946e-07
00:00:21.600,0.286091,0.595693,6.967187e-06,1.745522e-05,0.079238,0.004233,2.076972e-06
00:00:21.700,0.392377,0.477406,2.360064e-05,5.776709e-05,0.078323,0.004815,6.664025e-06
00:00:21.800,0.489402,0.381763,6.454404e-05,1.547635e-04,0.076806,0.005333,1.752874e-05
00:00:21.900,0.571732,0.308829,1.494586e-04,3.510416e-04,0.074620,0.005776,3.955961e-05
00:00:22.000,0.626201,0.227103,3.037155e-04,7.121265e-04,0.071707,0.006208,8.060106e-05
00:00:22.100,0.644455,0.128453,5.640686e-04,1.367271e-03,0.068084,0.006727,1.563728e-04
00:00:22.200,0.663422,0.078539,9.582043e-04,2.374470e-03,0.064641,0.007162,2.757907e-04
00:00:22.300,0.681611,0.050936,1.531243e-03,3.855556e-03,0.061496,0.007546,4.557967e-04
00:00:22.400,0.698613,0.036720,2.238601e-03,5.682021e-03,0.058719,0.007836,6.849170e-04
00:00:22.500,0.713968,0.029078,3.022105e-03,7.684976e-03,0.056320,0.008041,9.451509e-04
00:00:22.600,0.727435,0.024245,3.878385e-03,9.855390e-03,0.054264,0.008198,1.235783e-03
00:00:22.700,0.738463,0.019175,5.063385e-03,1.292285e-02,0.052505,0.008418,1.645565e-03
00:00:22.800,0.747827,0.015120,6.530821e-03,1.675728e-02,0.050987,0.008648,2.163440e-03
00:00:22.900,0.755460,0.011428,8.538902e-03,2.210289e-02,0.049675,0.008934,2.886474e-03
00:00:23.000,0.762411,0.009211,1.061115e-02,2.759370e-02,0.048527,0.009157,3.647745e-03

In [125]:
df_x = nn_test.get_df_xy('00:00:36.000', '00:00:37.000')
df_x

               Valence   Arousal
00:00:36.000 -0.214707  0.260461
00:00:36.100 -0.215263  0.259816
00:00:36.200 -0.183632  0.259228
00:00:36.300 -0.147168  0.258936
00:00:36.400 -0.117836  0.258876
00:00:36.500 -0.091053  0.258876
00:00:36.600 -0.067193  0.262077
00:00:36.700 -0.040169  0.265263
00:00:36.800 -0.026193  0.267305
00:00:36.900 -0.011659  0.269329
00:00:37.000  0.001245  0.270993

In [126]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 19-23%, Happy - 44-56%, Angry - 66-55%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:36.000,0.189787,0.446914,0.000195,0.661620,0.000168,0.000154,0.000912
00:00:36.100,0.184945,0.455178,0.000176,0.670441,0.000158,0.000153,0.000907
00:00:36.200,0.189195,0.478034,0.000159,0.661666,0.000151,0.000145,0.000883
00:00:36.300,0.196710,0.498410,0.000149,0.645577,0.000148,0.000137,0.000835
00:00:36.400,0.201433,0.516213,0.000143,0.634049,0.000147,0.000128,0.000784
00:00:36.500,0.206537,0.530494,0.000139,0.621547,0.000150,0.000119,0.000746
00:00:36.600,0.213259,0.539001,0.000133,0.606194,0.000154,0.000111,0.000718
00:00:36.700,0.216637,0.549414,0.000127,0.589583,0.000160,0.000107,0.000705
00:00:36.800,0.218805,0.557725,0.000121,0.583918,0.000159,0.000102,0.000706
00:00:36.900,0.219156,0.565864,0.000115,0.577523,0.000164,0.000101,0.000695
00:00:37.000,0.220346,0.569772,0.000110,0.568527,0.000171,0.000101,0.000689

In [127]:
nn_test.predict() # ПЛОХО! Neutral - 64-90% - err - 46-68%, Happy - 5-3% - err - 39-53%, 
# Angry - 35-4% - err - 31-52%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:36.000,0.802721,0.000821,0.069618,0.168661,0.029259,0.010011,0.042353
00:00:36.100,0.802610,0.000817,0.069651,0.168667,0.029175,0.009999,0.042529
00:00:36.200,0.827633,0.001418,0.067699,0.159132,0.029972,0.009831,0.036673
00:00:36.300,0.853122,0.002667,0.065513,0.148776,0.030960,0.009648,0.030854
00:00:36.400,0.871225,0.004425,0.063803,0.140892,0.031797,0.009508,0.026820
00:00:36.500,0.877876,0.007533,0.050561,0.109579,0.031998,0.009022,0.020092
00:00:36.600,0.878199,0.012233,0.036779,0.078535,0.032252,0.008499,0.014168
00:00:36.700,0.878847,0.021152,0.025609,0.053359,0.032498,0.007940,0.009552
00:00:36.800,0.878928,0.027956,0.021145,0.043436,0.032666,0.007668,0.007761
00:00:36.900,0.879076,0.037293,0.017324,0.035016,0.032830,0.007395,0.006256
00:00:37.000,0.879292,0.048068,0.014520,0.028900,0.032964,0.007159,0.005171

In [128]:
df_x = nn_test.get_df_xy('00:00:42.000', '00:00:42.500')
df_x

               Valence   Arousal
00:00:42.000 -0.431208  0.258913
00:00:42.100 -0.276828  0.258345
00:00:42.200 -0.126044  0.257805
00:00:42.300  0.012774  0.257292
00:00:42.400  0.132797  0.256804
00:00:42.500  0.236716  0.256341

In [129]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 50%, Happy - 18-46%, Angry - 61-22%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:42.000,0.502243,0.181685,0.000275,0.612893,0.003011,0.000579,0.002119
00:00:42.100,0.535251,0.241092,0.000246,0.517920,0.004662,0.000863,0.002023
00:00:42.200,0.544003,0.302449,0.000221,0.428494,0.006192,0.001107,0.001881
00:00:42.300,0.536196,0.361938,0.000196,0.349164,0.007338,0.001198,0.001740
00:00:42.400,0.522931,0.414101,0.000175,0.281304,0.008044,0.001221,0.001633
00:00:42.500,0.502529,0.461604,0.000155,0.224888,0.008423,0.001205,0.001563

In [130]:
nn_test.predict() # Более-менее. Neutral - 50-70% - err - 1-20%, Happy - 5-30% - err - 13-16%, 
# Angry - 35-0% - err - 26-21%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:42.000,0.570593,0.000020,0.084406,0.244380,0.023828,0.011105,0.114177
00:00:42.100,0.747993,0.000285,0.073592,0.187803,0.027420,0.010275,0.056927
00:00:42.200,0.866785,0.003872,0.064274,0.142823,0.031436,0.009524,0.027968
00:00:42.300,0.888880,0.064659,0.013859,0.026570,0.031602,0.006859,0.004924
00:00:42.400,0.834120,0.142850,0.003188,0.006082,0.030200,0.005611,0.001208
00:00:42.500,0.755161,0.217536,0.000896,0.001739,0.028878,0.004797,0.000370

In [131]:
df_x = nn_test.get_df_xy('00:00:42.500', '00:00:43.000')
df_x

               Valence   Arousal
00:00:42.500  0.236716  0.256341
00:00:42.600  0.321085  0.255900
00:00:42.700  0.388269  0.255482
00:00:42.800  0.446405  0.255151
00:00:42.900  0.496219  0.255151
00:00:43.000  0.541093  0.258207

In [132]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 50-38%, Happy - 46-61%, Angry - 22-7%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:42.500,0.502529,0.461604,0.000155,0.224888,0.008423,0.001205,0.001563
00:00:42.600,0.478964,0.499737,0.000136,0.178652,0.008664,0.001159,0.001451
00:00:42.700,0.460155,0.529674,0.000120,0.141405,0.008811,0.001105,0.001370
00:00:42.800,0.436789,0.558047,0.000108,0.111643,0.008762,0.001038,0.001290
00:00:42.900,0.412718,0.584249,0.000096,0.088029,0.008597,0.000969,0.001202
00:00:43.000,0.387863,0.610635,0.000088,0.069542,0.008211,0.000915,0.001102

In [133]:
nn_test.predict() # Более-менее. Neutral - 70-40% - err - 20-2%, Happy - 30-62% - err - 16-1%, 
# Angry - 0% - err - 22-7%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:42.500,0.755161,0.217536,0.000896,0.001739,0.028878,0.004797,0.000370
00:00:42.600,0.674747,0.296342,0.000320,0.000628,0.027841,0.004223,0.000142
00:00:42.700,0.602083,0.369534,0.000141,0.000279,0.027036,0.003815,0.000066
00:00:42.800,0.535182,0.438291,0.000069,0.000138,0.026359,0.003494,0.000034
00:00:42.900,0.476489,0.499427,0.000038,0.000076,0.025816,0.003241,0.000019
00:00:43.000,0.421531,0.556296,0.000021,0.000043,0.025585,0.003033,0.000011

In [134]:
df_x = nn_test.get_df_xy('00:00:47.000', '00:00:48.000')
df_x

               Valence   Arousal
00:00:47.000  0.402050  0.299550
00:00:47.100  0.402333  0.299550
00:00:47.200  0.403500  0.299481
00:00:47.300  0.406274  0.299384
00:00:47.400  0.406193  0.299230
00:00:47.500  0.415290  0.299125
00:00:47.600  0.418139  0.298942
00:00:47.700  0.423579  0.298760
00:00:47.800  0.431206  0.298555
00:00:47.900  0.440355  0.298336
00:00:48.000  0.450727  0.298102

In [135]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 71-69%, Happy - 40-45%
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:47.000,0.710237,0.407821,0.000096,0.005771,0.004438,0.000165,0.000185
00:00:47.100,0.711148,0.408063,0.000100,0.005730,0.004281,0.000168,0.000181
00:00:47.200,0.713677,0.409234,0.000102,0.005734,0.004085,0.000167,0.000180
00:00:47.300,0.714254,0.412195,0.000105,0.005921,0.003882,0.000161,0.000175
00:00:47.400,0.716460,0.412444,0.000108,0.006251,0.003699,0.000162,0.000173
00:00:47.500,0.713320,0.421777,0.000107,0.006487,0.003612,0.000162,0.000170
00:00:47.600,0.714224,0.424814,0.000107,0.006675,0.003599,0.000168,0.000171
00:00:47.700,0.710022,0.430272,0.000107,0.006693,0.003646,0.000182,0.000167
00:00:47.800,0.706393,0.437887,0.000105,0.006681,0.003628,0.000192,0.000165
00:00:47.900,0.701044,0.447169,0.000104,0.006814,0.003610,0.000197,0.000161
00:00:48.000,0.692921,0.457616,0.000106,0.006888,0.003541,0.000198,0.000157

In [136]:
nn_test.predict() # Плоховато на Neutral (Сойдёт). Neutral - 53-48% - err - 19%, Happy - 48-53% - err - 8%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:00:47.000,0.548818,0.409709,0.000084,0.000173,0.030928,0.003804,0.000038
00:00:47.100,0.548488,0.410046,0.000084,0.000172,0.030925,0.003803,0.000038
00:00:47.200,0.547183,0.411402,0.000083,0.000170,0.030903,0.003796,0.000037
00:00:47.300,0.544021,0.414667,0.000080,0.000164,0.030858,0.003780,0.000036
00:00:47.400,0.544249,0.414483,0.000080,0.000165,0.030844,0.003780,0.000036
00:00:47.500,0.533673,0.425359,0.000072,0.000148,0.030717,0.003728,0.000033
00:00:47.600,0.530485,0.428696,0.000070,0.000143,0.030663,0.003712,0.000032
00:00:47.700,0.524243,0.435181,0.000065,0.000134,0.030576,0.003682,0.000030
00:00:47.800,0.515438,0.444336,0.000060,0.000122,0.030459,0.003639,0.000027
00:00:47.900,0.504839,0.455385,0.000053,0.000110,0.030322,0.003589,0.000025
00:00:48.000,0.492807,0.467971,0.000047,0.000097,0.030169,0.003533,0.000022

In [137]:
df_x = nn_test.get_df_xy('00:01:06.000', '00:01:07.000') 
df_x

               Valence   Arousal
00:01:06.000 -0.103109  0.283163
00:01:06.100 -0.092284  0.282977
00:01:06.200 -0.085587  0.282701
00:01:06.300 -0.081722  0.282360
00:01:06.400 -0.070623  0.281872
00:01:06.500 -0.059186  0.281336
00:01:06.600 -0.049184  0.280761
00:01:06.700 -0.035158  0.280176
00:01:06.800 -0.022642  0.279583
00:01:06.900 -0.008292  0.278953
00:01:07.000 -0.001789  0.278458

In [138]:
df_y = nn_test.get_df_xy(xy = 'y') # Удивление (Neutral + Happy)
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:06.000,0.735105,0.152540,0.000869,0.255649,0.001597,0.000651,0.000894
00:01:06.100,0.734141,0.157158,0.000902,0.249441,0.001582,0.000660,0.000887
00:01:06.200,0.734078,0.159937,0.000916,0.245525,0.001590,0.000643,0.000889
00:01:06.300,0.734819,0.161817,0.000917,0.243539,0.001637,0.000628,0.000900
00:01:06.400,0.744191,0.165657,0.000897,0.236280,0.001662,0.000610,0.000898
00:01:06.500,0.753816,0.168743,0.000880,0.227929,0.001680,0.000600,0.000896
00:01:06.600,0.764034,0.169269,0.000862,0.218453,0.001695,0.000586,0.000879
00:01:06.700,0.775219,0.172246,0.000826,0.207403,0.001711,0.000575,0.000872
00:01:06.800,0.785698,0.174468,0.000797,0.197109,0.001756,0.000571,0.000872
00:01:06.900,0.793438,0.177854,0.000771,0.186146,0.001756,0.000576,0.000882
00:01:07.000,0.796028,0.178233,0.000745,0.180022,0.001700,0.000569,0.000939

In [139]:
nn_test.predict() # Средненько (Сойдёт)! Neutral - err 4-12%, Happy - err 11-15%, ANGRY - err 6-14%

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:06.000,0.859893,0.005169,0.049386,0.112640,0.034459,0.009521,0.019536
00:01:06.100,0.861245,0.006499,0.043265,0.097884,0.034412,0.009252,0.016893
00:01:06.200,0.862191,0.007494,0.039895,0.089721,0.034367,0.009089,0.015458
00:01:06.300,0.862865,0.008143,0.038115,0.085377,0.034322,0.008995,0.014705
00:01:06.400,0.864437,0.010305,0.033300,0.073746,0.034243,0.008733,0.012690
00:01:06.500,0.866065,0.013131,0.028962,0.063313,0.034159,0.008470,0.010902
00:01:06.600,0.867548,0.016229,0.025641,0.055367,0.034075,0.008246,0.009552
00:01:06.700,0.869453,0.021790,0.021567,0.045736,0.033980,0.007944,0.007920
00:01:06.800,0.871182,0.028307,0.018481,0.038524,0.033888,0.007683,0.006702
00:01:06.900,0.873106,0.038106,0.015468,0.031588,0.033788,0.007395,0.005532
00:01:07.000,0.874109,0.043598,0.014288,0.028893,0.033721,0.007266,0.005079

In [140]:
df_x = nn_test.get_df_xy('00:01:25.000', '00:01:26.000')
df_x

               Valence   Arousal
00:01:25.000  0.780514  0.429943
00:01:25.100  0.770180  0.429943
00:01:25.200  0.763402  0.429846
00:01:25.300  0.759536  0.429766
00:01:25.400  0.746653  0.429272
00:01:25.500  0.735193  0.428437
00:01:25.600  0.723706  0.427788
00:01:25.700  0.711666  0.427098
00:01:25.800  0.700324  0.426254
00:01:25.900  0.687633  0.425157
00:01:26.000  0.678700  0.423820

In [141]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 17-31, Happy 78-68
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:25.000,0.170274,0.782413,0.000291,0.001899,0.000740,0.000223,0.000262
00:01:25.100,0.184500,0.772122,0.000297,0.001941,0.000743,0.000216,0.000269
00:01:25.200,0.192932,0.765428,0.000299,0.002026,0.000752,0.000217,0.000271
00:01:25.300,0.197078,0.761560,0.000346,0.002024,0.000750,0.000216,0.000280
00:01:25.400,0.213567,0.748624,0.000404,0.001971,0.000785,0.000210,0.000304
00:01:25.500,0.234013,0.737090,0.000432,0.001897,0.000816,0.000200,0.000325
00:01:25.600,0.253310,0.725588,0.000472,0.001882,0.000829,0.000195,0.000335
00:01:25.700,0.271598,0.713548,0.000502,0.001882,0.000841,0.000194,0.000344
00:01:25.800,0.284844,0.702225,0.000512,0.001901,0.000863,0.000196,0.000349
00:01:25.900,0.300856,0.689563,0.000540,0.001930,0.000882,0.000197,0.000374
00:01:26.000,0.319784,0.680661,0.000564,0.001960,0.000893,0.000195,0.000386

In [142]:
nn_test.predict() # Neutral - 17-24% - err 0-7%, Happy 84-77% - err 6-1% - Здорово!

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:25.000,0.114719,0.858312,2.963341e-07,6.982929e-07,0.039939,0.002265,1.526825e-07
00:01:25.100,0.119765,0.851997,3.363758e-07,7.914596e-07,0.040109,0.002301,1.718100e-07
00:01:25.200,0.123215,0.847701,3.658118e-07,8.598188e-07,0.040209,0.002325,1.858053e-07
00:01:25.300,0.125230,0.845198,3.838148e-07,9.015818e-07,0.040263,0.002338,1.943360e-07
00:01:25.400,0.132240,0.836542,4.512397e-07,1.057639e-06,0.040414,0.002384,2.261603e-07
00:01:25.500,0.138917,0.828389,5.227130e-07,1.222451e-06,0.040499,0.002425,2.597593e-07
00:01:25.600,0.145810,0.819961,6.048294e-07,1.411534e-06,0.040608,0.002466,2.979349e-07
00:01:25.700,0.153341,0.810781,7.048390e-07,1.641316e-06,0.040721,0.002511,3.440166e-07
00:01:25.800,0.160815,0.801737,8.153553e-07,1.894493e-06,0.040803,0.002553,3.946254e-07
00:01:25.900,0.169598,0.791179,9.608204e-07,2.226764e-06,0.040876,0.002602,4.607707e-07
00:01:26.000,0.176292,0.783283,1.083242e-06,2.505017e-06,0.040854,0.002636,5.165251e-07

In [143]:
df_x = nn_test.get_df_xy('00:01:38.000', '00:01:39.000')
df_x

               Valence   Arousal
00:01:38.000  0.724162  0.396821
00:01:38.100  0.725256  0.395991
00:01:38.200  0.725922  0.395153
00:01:38.300  0.732286  0.394256
00:01:38.400  0.728995  0.393182
00:01:38.500  0.722660  0.391859
00:01:38.600  0.718987  0.390558
00:01:38.700  0.718649  0.389392
00:01:38.800  0.717313  0.388218
00:01:38.900  0.715846  0.386973
00:01:39.000  0.716951  0.385782

In [144]:
df_y = nn_test.get_df_xy(xy = 'y') # Neutral - 24-28, Happy 72-71
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:38.000,0.247921,0.727225,0.000302,0.002924,0.002745,0.003063,0.000617
00:01:38.100,0.245379,0.728168,0.000297,0.002864,0.002651,0.002912,0.000596
00:01:38.200,0.248069,0.728863,0.000286,0.002826,0.002657,0.002941,0.000590
00:01:38.300,0.249211,0.735282,0.000272,0.002743,0.002670,0.002996,0.000580
00:01:38.400,0.262386,0.731932,0.000260,0.002584,0.002722,0.002937,0.000555
00:01:38.500,0.279061,0.725456,0.000248,0.002368,0.002732,0.002796,0.000528
00:01:38.600,0.286941,0.721679,0.000234,0.002201,0.002678,0.002692,0.000514
00:01:38.700,0.286773,0.721287,0.000228,0.002108,0.002710,0.002639,0.000534
00:01:38.800,0.286524,0.719876,0.000228,0.002073,0.002824,0.002564,0.000535
00:01:38.900,0.286901,0.718372,0.000235,0.002071,0.002820,0.002526,0.000525
00:01:39.000,0.282643,0.719507,0.000245,0.002121,0.002750,0.002556,0.000521

In [145]:
nn_test.predict() # Нормас

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:38.000,0.159449,0.809587,7.646562e-07,0.000002,0.036826,0.002434,3.931105e-07
00:01:38.100,0.159144,0.810125,7.593318e-07,0.000002,0.036713,0.002429,3.911771e-07
00:01:38.200,0.159113,0.810335,7.580583e-07,0.000002,0.036606,0.002426,3.911890e-07
00:01:38.300,0.155546,0.814804,7.060365e-07,0.000002,0.036406,0.002402,3.667528e-07
00:01:38.400,0.158093,0.811965,7.412646e-07,0.000002,0.036332,0.002412,3.845509e-07
00:01:38.500,0.162738,0.806674,8.094161e-07,0.000002,0.036276,0.002434,4.184248e-07
00:01:38.600,0.165738,0.803361,8.552905e-07,0.000002,0.036182,0.002447,4.415580e-07
00:01:38.700,0.166521,0.802674,8.666517e-07,0.000002,0.036054,0.002447,4.480096e-07
00:01:38.800,0.167967,0.801199,8.890222e-07,0.000002,0.035940,0.002450,4.597944e-07
00:01:38.900,0.169546,0.799587,9.139387e-07,0.000002,0.035821,0.002455,4.729010e-07
00:01:39.000,0.169394,0.800022,9.100006e-07,0.000002,0.035670,0.002449,4.720701e-07

In [146]:
v = 2
dir_model = 'saved_models'
layer = 'first'
path_dir_model = os.path.join(project_dir_path, dir_model, layer, f'_{v}')
print(path_dir_model)
saved_models = list(os.walk(path_dir_model))[0]
save_name = f'model_{layer}_{N}_{v}'
path = os.path.join(path_dir_model, save_name)
path

/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_2

'/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_2/model_first_6_2'

In [147]:
model.save(path)

INFO:tensorflow:Assets written to: /home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/saved_models/first/_2/model_first_6_2/assets

In [148]:
model = load_model(path)

In [149]:
nn = NeuralNetwork(pa_vector_test, seven_vector_test, model)

/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/lib/nn_train/neural_network.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df_x[field] = self.df_x[field].apply(lambda entry: float(entry))
/home/ivan/Рабочий стол/Учёба/Git/NIR_1_sem_magistracy/lib/nn_train/neural_network.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df_y[field] = self.df_y[field].apply(lambda entry: float(entry))

In [150]:
#Last test

In [151]:
df_x = nn.get_df_xy('00:01:38.000', '00:01:39.000')
df_x

               Valence   Arousal
00:01:38.000  0.724162  0.396821
00:01:38.100  0.725256  0.395991
00:01:38.200  0.725922  0.395153
00:01:38.300  0.732286  0.394256
00:01:38.400  0.728995  0.393182
00:01:38.500  0.722660  0.391859
00:01:38.600  0.718987  0.390558
00:01:38.700  0.718649  0.389392
00:01:38.800  0.717313  0.388218
00:01:38.900  0.715846  0.386973
00:01:39.000  0.716951  0.385782

In [152]:
df_y = nn.get_df_xy(xy = 'y') # Neutral - 24-28, Happy 72-71
df_y

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:38.000,0.247921,0.727225,0.000302,0.002924,0.002745,0.003063,0.000617
00:01:38.100,0.245379,0.728168,0.000297,0.002864,0.002651,0.002912,0.000596
00:01:38.200,0.248069,0.728863,0.000286,0.002826,0.002657,0.002941,0.000590
00:01:38.300,0.249211,0.735282,0.000272,0.002743,0.002670,0.002996,0.000580
00:01:38.400,0.262386,0.731932,0.000260,0.002584,0.002722,0.002937,0.000555
00:01:38.500,0.279061,0.725456,0.000248,0.002368,0.002732,0.002796,0.000528
00:01:38.600,0.286941,0.721679,0.000234,0.002201,0.002678,0.002692,0.000514
00:01:38.700,0.286773,0.721287,0.000228,0.002108,0.002710,0.002639,0.000534
00:01:38.800,0.286524,0.719876,0.000228,0.002073,0.002824,0.002564,0.000535
00:01:38.900,0.286901,0.718372,0.000235,0.002071,0.002820,0.002526,0.000525
00:01:39.000,0.282643,0.719507,0.000245,0.002121,0.002750,0.002556,0.000521

In [153]:
nn.predict() # Neutral - err 5-1%, Happy 3% - НОРМ!

,Neutral,Happy,Sad,Angry,Surprised,Scared,Disgusted
00:01:38.000,0.159449,0.809587,7.646562e-07,0.000002,0.036826,0.002434,3.931105e-07
00:01:38.100,0.159144,0.810125,7.593318e-07,0.000002,0.036713,0.002429,3.911771e-07
00:01:38.200,0.159113,0.810335,7.580583e-07,0.000002,0.036606,0.002426,3.911890e-07
00:01:38.300,0.155546,0.814804,7.060365e-07,0.000002,0.036406,0.002402,3.667528e-07
00:01:38.400,0.158093,0.811965,7.412646e-07,0.000002,0.036332,0.002412,3.845509e-07
00:01:38.500,0.162738,0.806674,8.094161e-07,0.000002,0.036276,0.002434,4.184248e-07
00:01:38.600,0.165738,0.803361,8.552905e-07,0.000002,0.036182,0.002447,4.415580e-07
00:01:38.700,0.166521,0.802674,8.666517e-07,0.000002,0.036054,0.002447,4.480096e-07
00:01:38.800,0.167967,0.801199,8.890222e-07,0.000002,0.035940,0.002450,4.597944e-07
00:01:38.900,0.169546,0.799587,9.139387e-07,0.000002,0.035821,0.002455,4.729010e-07
00:01:39.000,0.169394,0.800022,9.100006e-07,0.000002,0.035670,0.002449,4.720701e-07